# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZXLUploadDome

inhibit_all_warnings!

target ‘ZXLUploadDome’ do
pod 'ZXLUpload', :path => '../'
pod 'TZImagePickerController'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'FMDB'
pod 'ZXLRecorder'
end
